config {
  type: "operations",
  description: "Se obtiene la transaccion final."
}

EXPORT DATA OPTIONS(
    uri = CONCAT(
  'gs://bucket_dmc_grupo04/gold/sql/Transaccion/',
  FORMAT_DATE('%Y/%m/%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)),
  '/transaccion_',
  FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)),
  '_*.parquet'),
  format='PARQUET',
  overwrite=true
) AS
SELECT *
FROM proyectointegrador-grupo04.gold.Transaccion;