-- models/bronze/bronze_centro_costo.sqlx
config {
  type: "incremental",
  schema: "bronze",
  database: "proyectointegrador-grupo04",
  name: "CentroCosto",
  bigquery: {
    partitionBy: "FechaCreacion"
  },
  tags: ["bronze"]
}

-- Siempre inserta lo que hay en sql_data (snapshot diario)
select
  IDCentroCosto,
  IDDependencia,
  CentroCosto,
  IDUnidadNegocio,
  FechaCreacion,
  FechaModificacion
from `proyectointegrador-grupo04.sql_data.CentroCosto`