-- models/bronze/bronze_unidad_negocio.sqlx
config {
  type: "incremental",
  schema: "bronze",
  database: "proyectointegrador-grupo04",
  name: "UnidadNegocio",
  bigquery: {
    partitionBy: "FechaCreacion"
  },
  tags: ["bronze"]
}

-- Siempre inserta lo que hay en sql_data (snapshot diario)
select
  IDUnidadNegocio,
  IDDependencia,
  UnidadNegocio,
  descripcion,
  FechaCreacion,
  FechaModificacion
from `proyectointegrador-grupo04.sql_data.UnidadNegocio`